<?php

	/**
	 * The Legend of Z
	 *
	 * @author	Oliver Hanraths <oliver.hanraths@uni-duesseldorf.de>
	 * @copyright	2014 Heinrich-Heine-Universität Düsseldorf
	 * @license	http://www.gnu.org/licenses/gpl.html
	 * @link	https://bitbucket.org/coderkun/the-legend-of-z
	 */
	
	namespace hhu\z\agents\bottomlevel;
	
	
	/**
	 * Agent to display a menu with Seminary related links.
	 * 
	 * @author	Oliver Hanraths <oliver.hanraths@uni-duesseldorf.de>
	 */
	class SeminarymenuAgent extends \nre\agents\BottomlevelAgent
	{
		
		
		
		
		/**
		 * Action: index.
		 */
		public function index(\nre\core\Request $request, \nre\core\Response $response)
		{
		}
		
	}

?>
