<?php

    /**
     * NRE
     *
     * @author      coderkun <olli@coderkun.de>
     * @copyright   2013 coderkun (http://www.coderkun.de)
     * @license     http://www.gnu.org/licenses/gpl.html
     * @link        http://www.coderkun.de/projects/nre
     */

    namespace nre\agents;


    /**
     * The BottomlevelAgent is the standard Agent and can have indefinite
     * SubAgents.
     * 
     * @author  coderkun <olli@coderkun.de>
     */
    abstract class BottomlevelAgent extends \nre\core\Agent
    {
    }

?>
